---
- hosts: dockTest
  become: yes
  
  tasks:
    - name: Patching
      yum: name=* update_cache=yes state=latest
    
    - name: Disable SELinux
      selinux:
        state: disabled
    
    - name: Uninstalling old versions
      yum:
        state: absent
        name:
            - docker
            - docker-client
            - docker-client-latest
            - docker-common
            - docker-latest
            - docker-latest-logrotate
            - docker-logrotate
            - docker-engine
            
    - name: Installing Prerequisites 
      yum:
        state: latest
        name:
            - yum-utils
            - device-mapper-persistent-data
            - lvm2
            - bash-completion 
            - curl
            - wget
            - telnet
      
    - shell: source /etc/profile.d/bash_completion.sh