# Author: Akik
# Email:  akik22@gmail.com
# ReadMe: This script is for Installing Docker. Tested on CentOS7 but not tested on CentOS8.
#         Run this script from Ansible. Add the desired hosts on ansible and then run it. Modification/Changes/Constructive criticism are welcome
#         This will patch your system first so be patient at first.
#         Ansible User should have sudo permissions with no password facility

---
- hosts: dockTest
  become: yes
  
  tasks:
    - name: Patching
      yum: name=* update_cache=yes state=latest
    
    - name: Disable SELinux
      selinux:
        state: disabled
    
    - name: Uninstalling old versions of docker
      yum:
        state: absent
        name:
            - docker
            - docker-client
            - docker-client-latest
            - docker-common
            - docker-latest
            - docker-latest-logrotate
            - docker-logrotate
            - docker-engine
            
    - name: Installing Prerequisites 
      yum:
        state: latest
        name:
            - yum-utils
            - device-mapper-persistent-data
            - lvm2
            - bash-completion 
            - curl
            - wget
            - telnet
      
    - shell: source /etc/profile.d/bash_completion.sh

    - name: Installing, Starting and Enabling Docker
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - yum:
        update_cache : yes
        state: latest
        name:
            - docker-ce 
            - docker-ce-cli 
            - containerd.io
    
    - service: name=docker state=started enabled=yes
    
    - name: Installing Docker Compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - file: dest=/usr/local/bin/docker-compose mode=a+x

    - file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
    
    - name: Installing Docker Bash Completion
      shell: curl -L https://raw.githubusercontent.com/docker/compose/1.25.0/contrib/completion/bash/docker-compose -o /etc/bash_completion.d/docker-compose
      args:
        creates: /etc/bash_completion.d/docker-compose

    - shell: source /etc/bash_completion.d/docker-compose